
[general]
	#While set to true, the eyes entity will ignore the artificial light level and will jumpscare even if it's lit. Daylight will still disable it's AI.
	eyesCanAttackWhileLit = true
	#Set to false to disable the jumpscare system.
	jumpscare = false
	#Set to a number > 0 to cause the jumpscare to apply poison the player. A value of 5 will take around half of the health. 
	#Range: 0 ~ 6
	jumpscareHurtLevel = 0

[eye_aggression]
	#While set to true, the eyes entities will have higher aggression values on lower light levels.
	lightLevel = false
	#While set to true, the eyes entities will spawn with higher aggresion levels in higher local difficulties.
	localDifficulty = true
	#While set to true, the eyes entities will progressively get more bold, and move faster, the longer they live.
	enableEscalation = false

