#Base absorption amount to give to players in half hearts, replenishes like regular health. If 0, players will start with no absorption.
#Range: 0 ~ 20
base_absorption = 0
#If true, hearts from the potion effect will be included in absorption calculations. This means absorption from potions will replenish during the timer mostly.
include_potion = false
#Absorption efficiency boost per chain armor piece. Absorption efficiency decreases hunger consumption and hunger requirements to heal.
#Range: 0.0 ~ 4.0
gold_absorption = 1
#Maximum level for the enchantment per piece. Each level gives half a heart. If 0, enchantment will be disabled.
#Range: 0 ~ 6
max_enchantment_level = 4
#If true, shields can receive the absorption enchant through an anvil. The enchant will apply when the shield is in the offhand
enchant_shields = true
#If true, armor grants absorption hearts instead of armor values and absorption efficiency instead of toughness. Should work with most mods. May want to reconsider gold and chain bonuses if you enable this.
replace_armor = true

