
#Spawn Settings
["Spawn Settings"]
	#Candidate Group Minimum Size
	#Range: > 1
	candidate_min_spawn_size = 1
	#Candidate Spawn Group Maximum Size
	#Range: > 1
	candidate_max_spawn_size = 1
	#Candidate Spawn Chance Probability
	#Range: > 1
	candidate_chance = 1
	#Candidate Spawn Dimension Blacklist
	candidate_dimensions = []

