"make Enchanted Mob can Spawn Natural" = true
"maje Enchanted Animal can Spawn Natural" = false
"make Enchanted Boss Monster can spawn" = false
"when this config turn on,you can enchant yourself" = true

