
[General]
	#The radius around the campfire in blocks where players receive the regeneration effect.
	#Range: 1 ~ 64
	healingRadius = 16
	#The level of regeneration which the campfire applies, by default 1.
	#Range: 1 ~ 50
	regenerationLevel = 1
	#When enabled, hides the particles from the regeneration effect around the campfire.
	hideEffectParticles = true
	#When enabled, the mod will work with soul campfires.
	enableEffectForSoulCampfires = true
	#The duration of the regeneration effect which the campfire applies.
	#Range: 1 ~ 600
	effectDurationSeconds = 60
	#When enabled, the campfire only has an effect when the block is signalling.
	campfireMustBeSignalling = false
	#When enabled, the campfire heals passive mobs around where the radius is half the width of a bounding box.
	healPassiveMobs = true
	#When enabled, the mod will work with normal campfires.
	enableEffectForNormalCampfires = true
	#How often in ticks the mod checks for campfires around the player. 1 second = 20 ticks, so by default every 2 seconds.
	#Range: 1 ~ 1200
	checkForCampfireDelayInTicks = 40
	#When enabled, the campfire only has an effect when the block is lit up.
	campfireMustBeLit = true

