
[Temples]
	#
	# Add the ID/resource location of the biome you don't want
	# temples to spawn in. Separate each ID with a comma ,
	#
	#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedTempleBiomes = ""
	#
	# Add Nether Crimson Temples to modded Nether Crimson Forest biomes.
	addNetherCrimsonTempleToModdedBiomes = true
	#
	# How rare are Nether Basalt Temples in Nether Basalt Delta biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherBasaltTempleSpawnrate = 27
	#
	# Add Nether Soul Temples to modded Nether Soul Sand Valley biomes.
	addNetherSoulTempleToModdedBiomes = true
	#
	# How rare are Nether Temples in Nether Wastelands.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherWastelandTempleSpawnrate = 27
	#
	# How rare are Nether Soul Temples in Nether Soul Sand Valley.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherSoulTempleSpawnrate = 27
	#
	# Add Nether Basalt Temples to modded Nether Basalt biomes.
	addNetherBasaltTempleToModdedBiomes = true
	#
	# Add Nether Wasteland Temples to modded Nether biomes
	# that other nether temples don't fit in.
	addNetherWastelandTempleToModdedBiomes = true
	#
	# How rare are Nether Crimson Temples in Nether Crimson Forest.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherCrimsonTempleSpawnrate = 27
	#
	# Add Nether Warped Temples to modded Nether Warped Forest biomes.
	addNetherWarpedTempleToModdedBiomes = true
	#
	# How rare are Nether Crimson Temples in Nether Warped Forest.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherWarpedTempleSpawnrate = 27

[Pyramids]
	#
	# Add Nether Pyramids to modded Nether biomes.
	addNetherPyramidToModdedBiomes = true
	#
	# How rare are Nether Pyramids in Nether.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	netherPyramidSpawnrate = 37
	#
	# How rare are Badlands Pyramid in non-plateau Badlands biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	badlandsPyramidSpawnrate = 20
	#
	# Add the ID/resource location of the biome you don't want
	# pyramids to spawn in. Separate each ID with a comma ,
	#
	#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedPyramidBiomes = ""
	#
	# Add Badlands Pyramid to modded Badlands biomes.
	addBadlandsPyramidToModdedBiomes = true

