
#Simple Tomb config
[simpletomb]

	[simpletomb.tomb]
		#The radius in which extra bonus items should be hunted for and collected when a grave is spawned; set to zero (0) to disable
		#Range: 0 ~ 16
		extra_items = 2
		#Whether to handle player death at all (false will disable almost the entire mod)
		enabled = true

	[simpletomb.teleport]
		#When survival player is within this (straight line calculated) distance from the tomb, they can teleport to the tomb.  Set as zero (0) to disable survival TP feature.   Set as negative one (-1) to allow survival teleportation always and ignore the distance (within dimension) 
		#Range: -1 ~ 128
		survival = 16
		#If creative mode players can teleport to the tomb with the key, ignoring distance
		creative = true

	[simpletomb.key]
		#Whether to give a Grave Key item to the player on death.  Grave can be opened without they key, but the key will help the player locate the grave
		given = true
		#If a key is being dropped, will the player's display name be added to the tomb key item name
		named = true

