disabledMasks = []
#Range: 0 ~ 100
masksChance = 42
#Entity chance override. Each entry should be a resource location and a chance, separated by a comma. EG: "minecraft:pig,100" will make all minecraft pigs have a 100% chance of having Googly Eyes.
entityOverrideChance = []
#Entities with these names will always have Googly Eyes.
nameOverride = []

