
#Wildfire Spawn Settings
["Wildfire Spawn Settings"]
	#Wildfire Spawn Chance on Flammable Blocks
	#Range: > 1
	wildfire_chance = 5
	#Wildfire Spawn Chance on Non-Flammable Blocks
	#Range: > 1
	wildfire_chance_non_flam = 15
	#Wildfire Spawn Dimension Blacklist
	wildfire_dimensions = []

