
#Gui Configs
[gui]
	#Textformatting codes for the display of the difficulty
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	"Difficulty color" = "DARK_PURPLE"
	#Scaling of the difficulty text
	"Text Scale" = 1.0
	"Gui Y" = 5
	"Gui X" = 5

